config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources:poohs
 root 'poohs#index'
 
 get 'users' =>'users#index'

 resources :perfumes
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/pooh.rb
class Pooh < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader

# image_topメソッドとimagesメソッドを使用できるようにする。


has_many_attached :images

has_many :pooh_tag_relations, dependent: :destroy
has_many :tags, through: :pooh_tag_relations, dependent: :destroy

end

app/models/pooh_tag_relation.rb
class PoohTagRelation < ApplicationRecord
  belongs_to :pooh
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :pooh_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :poohs, through: :pooh_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :poohs 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end

    def new
        @perfume = Perfume.new
    end

    def show
        @perfume = Perfume.find_by(id: params[:id])
    end

    def create
        perfume = Perfume.new(perfume_params)
        if perfume.save
            flash[:notice] = "診断が完了しました"
            redirect_to perfume_path(perfume.id)
        else
            redirect_to :action => "new"
        end
    end
end

private
    def perfume_params
        params.require(:perfume).permit(:question1, :question2, :question3, :question4)
    end

app/controllers/poohs_controller.rb
class PoohsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]
    def index
        @poohs = Pooh.all
      if params[:tag]
        Tag.create(name: params[:tag], category: params[:category])
      end

      if params[:tag_ids]
        @poohs = []
        params[:tag_ids].each do |key, value|      
          @poohs += Tag.find_by(name: key).poohs if value == "1"
        end
        @poohs.uniq!
      end
    end

    def new
        @pooh = Pooh.new
      end
    
      def create
        @pooh = Pooh.new(pooh_params)
        
        @pooh.user_id = current_user.id

        if @pooh.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def show
        @pooh = Pooh.find(params[:id])
      end

      def edit
        @pooh = Pooh.find(params[:id])
      end

      def update
        pooh = Pooh.find(params[:id])
        if pooh.update(pooh_params)
          redirect_to :action => "show", :id => pooh.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        pooh = Pooh.find(params[:id])
        pooh.destroy
        redirect_to action: :index
      end

      private
      def pooh_params
        params.require(:pooh).permit(:food_name, :gi_value, :energy, :protein, :lipid, :carbo, :salt, :effect, :treat, :recipe, :created_at, :image, :beauty, :pain, :recovery, :mental, :woman, :nil, tag_ids: [])
      end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/poohs_helper.rb
module PoohsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perfumes/index.html.erb
<h1>診断スタート</h1>
<%= link_to "診断を始める", new_perfume_path, class: "link" %>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="perfume-container">

        <div class="col-12">
            <p>Q1. 今の体調は？</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">元気</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">体調不良</label>
            <%= f.radio_button :question1, "3", id: "custom_id3" %>
            <label for="custom_id3">胃腸の調子が悪い</label>
        </div>

        <div class="col-12">
            <p>Q2. 理想の身体は？</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id4" %>
            <label for="custom_id4">免疫強化</label>
            <%= f.radio_button :question2, "2", id: "custom_id5" %>
            <label for="custom_id5">筋肉増強</label>
            <%= f.radio_button :question2, "3", id: "custom_id6" %>
            <label for="custom_id6">脂肪減少</label>
        </div>   

        <div class="col-12">
            <p>Q3. 提案してほしいジャンル</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id7" %>
            <label for="custom_id7">和食</label>
            <%= f.radio_button :question3, "2", id: "custom_id8" %>
            <label for="custom_id8">洋食</label>
            <%= f.radio_button :question3, "3", id: "custom_id9" %>
            <label for="custom_id9">中華</label>
            <%= f.radio_button :question3, "5", id: "custom_id11" %>
            <label for="custom_id11">デザート</label>
        </div>
    

    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
  <% end %>
  

app/views/perfumes/show.html.erb
<div class="intoro">
  <h5>診断結果</h5>
  <p>あなたにおすすめの食材は…</p>
</div>
<div class="perfume-container">
  <% case [@perfume.question1, @perfume.question2, @perfume.question3] %>
  <% when ["1", "1", "1"] %>
    <h6>元気・免疫UPできる和食</h6>

    <p>鶏肉とナスの甘酢みそ炒め</p>
    <p>→鶏肉・味噌・お酢（疲労回復）</p>


    <p>ショウガ・納豆・海藻・さつまいも・牛ひれ肉・豆腐・鯖・キノコ・長いも・鶏むね肉・味噌・大根・小松菜・かぼちゃ</p>


    <p>ビタミン類→粘膜・皮膚を強くする（物理的なバリア）</p>
    <p>ポリフェノール・緑黄色野菜→活性酸素（タンパク質に悪影響）を減らす・無害化→細胞の変質による病気（がんなど）・生活習慣病（動脈硬化など）の予防</p>
    <p>タンパク質→免疫抗体作り→感染症の回復はやめる・かかりにくくなる</p>
    <p>食物繊維→体に悪いもの（毒素など）の排出を促す</p>
    <p>発酵食品→善玉菌（免疫細胞を活性化）


  <% when ["1", "1", "2"] %>
    <h6>元気・免疫UPできる洋食</h6>

    <p>ニンジンとショウガのポタージュ</p>
    <p>→しょうが・人参</p>

    <p>チキンときのこのサラダ</p>
    <p>→チキン・キノコ</p>

    <p> 野菜たっぷりカレースープ</p>
    <p>→鶏肉・ショウガ・ニンニク・人参・キノコ・かぼちゃ・パプリカ・ピーマン・はちみつ</p>

    <p>たっぷりきのこのポテトグラタン</p>
    <p>→きのことジャガイモを一緒に取るとよい！</p>

  <% when ["1", "1", "3"] %>
    <h6>元気・免疫UPできる中華</h6>

    <p>たっぷりニラの麻婆豆腐</p>
    <p>→ニンニク・豆腐・長ネギ</p>
    
    <p>海老としいたけの蒸し団子</p>
    <p>→しいたけの食物繊維・えびはんぺんのタンパク質</p>

    <p>にんにく・海藻・きのこ・豆腐</p>
    <p>ストレスを緩和してくれる効果がある</p>



  <% when ["1", "1", "5"] %>
    <h6>元気・免疫UPできるデザート</h6>

    <p>ヨーグルト・さつまいも・リンゴ・バナナ</p>
    <p>幸福感を得やすい</p>




  <% when ["1", "2", "1"] %>
    <h6>元気・筋肉増強できる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["1", "2", "2"] %>
    <h6>元気・筋肉増強できる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["1", "2", "3"] %>
    <h6>元気・筋肉増強できる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  

  <% when ["1", "2", "5"] %>
    <h6>元気・筋肉増強できるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>


    <% when ["1", "2", "1"] %>
    <h6>元気・脂肪減少できる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["1", "3", "2"] %>
    <h6>元気・脂肪減少できる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["1", "3", "3"] %>
    <h6>元気・脂肪減少できる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  

  <% when ["1", "3", "5"] %>
    <h6>元気・脂肪減少できるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>






    <% when ["2", "1", "1"] %>
    <h6>体調不良・免疫UPできる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["2", "1", "2"] %>
    <h6>体調不良・免疫UPできる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["2", "1", "3"] %>
    <h6>体調不良・免疫UPできる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>


  <% when ["2", "1", "5"] %>
    <h6>体調不良・免疫UPできるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>


    <% when ["2", "2", "1"] %>
    <h6>体調不良・筋肉増強できる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["2", "2", "2"] %>
    <h6>体調不良・筋肉増強できる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["2", "2", "3"] %>
    <h6>体調不良・筋肉増強できる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>



  <% when ["2", "2", "5"] %>
    <h6>体調不良・筋肉増強できるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>


    <% when ["2", "3", "1"] %>
    <h6>体調不良・脂肪減少できる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["2", "3", "2"] %>
    <h6>体調不良・脂肪減少できる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["2", "3", "3"] %>
    <h6>体調不良・脂肪減少できる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>


  <% when ["2", "3", "5"] %>
    <h6>体調不良・脂肪減少できるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>





    <% when ["3", "1", "1"] %>
    <h6>胃腸の調子が悪い・免疫UPできる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["3", "1", "2"] %>
    <h6>胃腸の調子が悪い・免疫UPできる洋食</h6>

    <p>小松菜と高野豆腐のヨーグルトスープ</p>
    <p>→ヨーグルト・豆腐・野菜</p>



  <% when ["3", "1", "3"] %>
    <h6>胃腸の調子が悪い・免疫UPできる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  

  <% when ["3", "1", "5"] %>
    <h6>胃腸の調子が悪い・免疫UPできるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>


    <% when ["3", "2", "1"] %>
    <h6>胃腸の調子が悪い・筋肉増強できる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["3", "2", "2"] %>
    <h6>胃腸の調子が悪い・筋肉増強できる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["3", "2", "3"] %>
    <h6>胃腸の調子が悪い・筋肉増強できる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  

  <% when ["3", "2", "5"] %>
    <h6>胃腸の調子が悪い・筋肉増強できるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>


    <% when ["3", "3", "1"] %>
    <h6>胃腸の調子が悪い・脂肪減少できる和食</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>


  <% when ["3", "3", "2"] %>
    <h6>胃腸の調子が悪い・脂肪減少できる洋食</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>


  <% when ["3", "3", "3"] %>
    <h6>胃腸の調子が悪い・脂肪減少できる中華</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  

  <% when ["3", "3", "5"] %>
    <h6>胃腸の調子が悪い・脂肪減少できるデザート</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>


  <% end %>
</div>

app/views/poohs/edit.html.erb
<%= form_for @pooh do |f| %>
    <%= f.label :食べ物の名前 %>
    <%= f.text_field :food_name, :size => 140 %>

    <%= f.label :画像 %>
    <%= f.file_field :image %>

    <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
                <%= tag.check_box class: 'form-check-input' %>
                <%= tag.text %>
            <% end %>
        </div>
    <% end %>
</div>
    <%= f.label :GI値 %>
    <%= f.text_field :gi_value, :size => 140 %> 
    <%= f.label :熱量 %>
    <%= f.text_field :energy, :size => 140 %>
    <%= f.label :タンパク質 %> 
    <%= f.text_field :protein, :size => 140 %> 
    <%= f.label :脂質 %>
    <%= f.text_field :lipid, :size => 140 %> 
    <%= f.label :炭水化物 %>
    <%= f.text_field :carbo, :size => 140 %> 
    <%= f.label :食塩相当量 %>
    <%= f.text_field :salt, :size => 140 %>

    <%= f.label :効能 %> 
    <%= f.text_field :effect, :size => 140 %> 
    <%= f.label :調理法・保存方法 %>
    <%= f.text_area :treat, :size => "140x10" %> 
    <%= f.label :レシピ %>
    <%= f.text_area :recipe, :size => "30x2" %> 
    
    <%= f.submit "編集する" %>
  <% end %>

 

app/views/poohs/index.html.erb
<% if params[:tag_ids] %>
  <h1>食材一覧</h1>
  <% @poohs.each do |t| %>
    <div class="pooh">
    
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.user.email %>
        <%= t.food_name %>
        <%= link_to "詳細へ", pooh_path(t.id) %>
        <%= link_to "編集する", edit_pooh_path(t.id) %>
        <%= button_to "削除する", pooh_path(t.id), method: :delete %>
    </div>
  <% end %>
<% else %>
 
  <h1>効能一覧</h1>
  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= link_to "新規投稿へ", new_pooh_path %>


      <%= form_tag({controller:"poohs",action:"index"}, method: :get) do %>
      <%= text_field_tag :tag %>
      <%= select_tag  "category", raw("<option>美容系</option><option>痛み系</option><option>体力系</option><option>精神系</option><option>女性系</option>")%>
      <%= submit_tag 'タグを追加' %>
      <% end %>
    <% end %>
  <% end %>
    
  <%= form_tag({controller:"poohs",action:"index"}, method: :get) do %>

    <div class="biyou">
      <div class="biyouname">
        美容系
      </div>
      <div class="biyoutag">
        <% Tag.where(category:"美容系").each do |t| %>
          <label class="tag">
          <li><%= check_box :tag_ids, t.name %>
          <span>
          <%= t.name %>
          </span>
          </li>
          </label>
        <% end %>
      </div>
    </div>

    <div class="itami">
      <div class="itaminame">
       痛み系
      </div>
      <div class="itamitag">
        <% Tag.where(category:"痛み系").each do |t| %>
          <label class="tag">
          <li><%= check_box :tag_ids, t.name %>
          <span>
          <%= t.name %>
          </span>
          </li>
          </label>
        <% end %>
      </div>
    </div>

    <div class="tairyoku">
      <div class="tairyokuname">
        体力系
      </div>
      <div class="tairyokutag">
        <% Tag.where(category:"体力系").each do |t| %>
          <label class="tag">
          <li><%= check_box :tag_ids, t.name %>
          <span>
          <%= t.name %>
          </span>
          </li>
          </label>
        <% end %>
      </div>
    </div>

    <div class="seishin">
      <div class="seishinname">
        精神系
      </div>
      <div class="seishintag">
        <% Tag.where(category:"精神系").each do |t| %>
          <label class="tag">
          <li><%= check_box :tag_ids, t.name %>
          <span>
          <%= t.name %>
          </span>
          </li>
          </label>
        <% end %>
      </div>
    </div>

    <div class="zyosei">
      <div class="zyoseiname">
        女性系
      </div>
      <div class="zyoseitag">
        <% Tag.where(category:"女性系").each do |t| %>
          <label class="tag">
          <li><%= check_box :tag_ids, t.name %>
          <span>
          <%= t.name %>
          </span>
          </li>
          </label>
        <% end %>
      </div>
    </div>

    <%= submit_tag '検索' %>
  <% end %>
  
  <%= link_to"診断はこちら",new_perfume_path,class:"get" %>
  
<% end %>

<% if user_signed_in? %>
  <%= button_to 'ログアウト', destroy_user_session_path,method: :delete %>
<% else %>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %>
<% end %>

app/views/poohs/new.html.erb
<h1>Winnie_the_Pooh</h1>
<h3>新規食材</h3>

<%= form_for @pooh do |f| %>


  <div class='form-group'>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
  <% end %>
</div>
    

<div class="field">
<%= f.label :food_name %>
<%= f.text_field :food_name, :size => 30 %>
</div>

<span class="image-top">
        <%= f.label :サムネイル %>
        <%= f.file_field :image %>
      </span>

<div class="field">
<%= f.label :gi_value %>
<%= f.text_field :gi_value, :size => 30 %>
</div>

 <div class="field">
    <%= f.label :energy %>
    <%= f.text_field :energy, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :protein %>
    <%= f.text_field :protein, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :lipid %>
    <%= f.text_field :lipid, :size => 30 %>
  </div>

  <div class="field">
  <%= f.label :carbo %>
  <%= f.text_field :carbo, :size => 30 %>
</div>

<div class="field">
<%= f.label :salt %>
<%= f.text_field :salt, :size => 30 %>
</div>

# データ型がintegerで数字のみを入力するフォーム
  <div class="field">
    <%= f.label :user_id  %>
    <%= f.number_field :user_id, :size => 10 %>
  </div>

# データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :recipe  %>
    <%= f.text_area :recipe, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :treat  %>
    <%= f.text_area :treat, :size => "140x10" %>
  </div>

  <div class="field">
    <%= f.label :effect  %>
    <%= f.text_area :effect, :size => "30x2" %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", poohs_path %>


app/views/poohs/show.html.erb
<h3>食材の詳細</h3>
<div class="pooh">

  <div class="samune" style="background-image: url('<%= @pooh.image %>');">
      <div class="name">
      <%= @pooh.food_name %>
    </div>
  </div>

  <div class="set">
   <div class="image">
   </div>

   <div class="seibun">
   <p><%= @pooh.gi_value %></p>
   <p><%= @pooh.energy %></p>
   <p><%= @pooh.protein %></p>
   <p><%= @pooh.lipid %></p>
   <p><%= @pooh.carbo %></p>
   <p><%= @pooh.salt %></p>
   </div>
  </div>

  <div class="effect">
   <p><%= @pooh.effect %></p>
  </div>
  <a href="#" class="effect">BUTTON</a>

  <div class="treat">
   <%= simple_format(@pooh.treat) %>
   <p></p>
  </div>

  <div class="recipe">
   <p><%= @pooh.recipe %></p>
  </div>

</div>

<% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= link_to "編集する", edit_pooh_path(@pooh.id) %>

    <% end %>
  <% end %>

<%= link_to "食材一覧に戻る", poohs_path %>

app/views/users/index.html.erb
<% if user_signed_in? %>
<% if current_user.admin? %>
  <% sum = 0 %>
    <% @users.each do |u| %>
      <p>メアド:<%= u.email %></p>
      <p>名前:<%= u.name %>さん</p>
    <% sum += 1 %>
    <% end %>
  <p>登録者合計：<%= sum %></p>
 <% end %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>